export enum CommandIds {
  ChangeWorkspace = 'changeWorkspace',
  GenerateCustomComponent = 'generateCustomComponent',
  GenerateComponent = 'generateComponent',
  GeneratePage = 'generatePage',
  GenerateStore = 'generateStore',
  GenerateRouter = 'generateRouter',
  GenerateComposable = 'generateComposable',
  GenerateDirective = 'generateDirective',
  GenerateMiddleware = 'generateMiddleware',
  GenerateModel = 'generateModel',
  GenerateLayout = 'generateLayout',
  GenerateService = 'generateService',
  GenerateTest = 'generateTest',
  GenerateEnum = 'generateEnum',
  GenerateConstant = 'generateConstant',
  GenerateHook = 'generateHook',
}
